[package]
name = "lixploy"
description = "AHQ Store AppImage deployer"
version = "0.0.2"
edition = "2021"

[dependencies]
tokio = { version = "1", features = [
  "fs",
  "process",
  "time",
  "io-std",
  "macros",
  "rt",
] }
